# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11 and Maven
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build and Test with Maven
      env:
          USERNAME: ${{ secrets.USERNAME }}
          TOKEN: ${{ secrets.TOKEN }}  
      run: mvn clean install -Dusername=$USERNAME -Dtoken=$TOKEN
      
    - name: Upload target folder
      uses: actions/upload-artifact@v2
      with:
         name: target
         path: |
           ${{ github.workspace }}/target
           ${{ github.workspace }}/reports
      
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
         name: Test Results
         path: ${{ github.workspace }}/target/surefire-reports/TEST-TestSuite.xml
         reporter: java-junit
         java-version: 11
